//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOfVegsSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.orders = new HashSet<order>();
            this.purchasedProducts = new HashSet<purchasedProduct>();
            this.userReviews = new HashSet<userReview>();
        }
    
        public int productID { get; set; }
        [Required(ErrorMessage = "Product name is required")]
        [MinLength(3), MaxLength(50)]
        public string productName { get; set; }
        [MaxLength(500)]
        public string description { get; set; }
        public string imageUrl { get; set; }
        [Required(ErrorMessage = "Category is required")]
        public int categoryID { get; set; }
        public Nullable<decimal> purchasedPrice { get; set; }
        public Nullable<int> profitPercentage { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<decimal> sellPrice { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchasedProduct> purchasedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userReview> userReviews { get; set; }
    }
}
