//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOfVegsSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchasedProduct
    {
        public int purchasedProductID { get; set; }
        public int purchaseID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public Nullable<decimal> purchasedPrice { get; set; }
    
        public virtual purchase purchase { get; set; }
        public virtual product product { get; set; }
    }
}
